### ISSUE TITLE
How to use authentication proxy in GeoApiContext

### ISSUE THREAD

**Issue by ghost** [googlemaps/google-maps-services-java#141]
I have access google api through proxy with authentication, but there seems no method in GeoApiContext could set authentication for OkClient.
I want to know if there is a way to do this? 
Thanks

**Comment by markmcd** [comment]
You can use the `setProxy()` call on `GeoApiContext`. For details on how to set up auth on a `java.net.Proxy`, check out [this answer on Stack Overflow](http://stackoverflow.com/q/1626549/17328).

**Comment by lhomme-a** [comment]
This is not a solution because the proxyAuthenticator in OkHttpClient.builder is still equals to Authenticator.NONE and the java.net.Authenticator is not use in this case.
The GeoApiContext.builder need to expose a proxyAuthenticator method and delagate it to its inner builder.
Can you reopen this issue ?

**Comment by domesticmouse** [comment]
Feel free to submit a PR with your suggested change.

**Comment by domesticmouse** [comment]
I believe this issue is now fixed. Please comment to re-open if I've missed something. Thanks!
