### ISSUE TITLE
I want get steps. How to code that

### ISSUE THREAD

**Issue by sudehs** [googlemaps/google-maps-services-java#147]
Hi, 

I want to print all steps in System.out.println ().

DirectionsResult result = DirectionsApi.getDirections(context, "Kalutara","Ratmalana").await();
System.out.println(result.routes[0].legs[0].steps[0]);

what i got as output is 

com.google.maps.model.DirectionsStep@1ff8b8f

please help me to figure this out.

**Comment by russellhoff** [comment]
@sudehs Why you don't iterate over the steps' array as usual?

The output you are printing is due to the fact that the class you want to print hasn't the toString() method implemented (overriden, which is inherited by any class from Object parent). Therefore, you will have to print manually each field (see javadoc [here](http://googlemaps.github.io/google-maps-services-java/v0.1.3/javadoc/com/google/maps/model/DirectionsStep.html)).

**Comment by domesticmouse** [comment]
We aren't going to add toString() methods to the model classes, as we expect each developer to have their own specific output medium of choice, be it HTML or Swing.
