### ISSUE TITLE
Serializable GeoApiContext Class for Spark Processing

### ISSUE THREAD

**Issue by itsmeccr** [googlemaps/google-maps-services-java#206]
How can I serialize GeoApiContext class so that I can pass a single instance of GeoApiContext to a function?

**Comment by domesticmouse** [comment]
GeoApiContext is not designed to be serialized, as it is an owner of a thread pool. I'd suggest that passing a GeoApiContext to a Spark cluster is probably the wrong way to think about your problem. The intent of the GeoApiContext is to enable you to throttle your requests and obey your API quota limits. Running a Spark cluster against the Google Maps web services sounds like a recipe for quota draining at a rapid clip.

**Comment by jbenoit2011** [comment]
`GeoApiContext` is perfectly usable in Spark Applications in cluster mode. Initialize it in the same class as your Spark session, usually your Main class. Then use it whenever you want. But be careful about the `qps` setting: since the context is not shared between nodes, you have to divide the max QPS allowed by the number of cores and task nodes. (e.g: you want to allow max 90QPS, you have 2 cores and 1 task, so set `queryRateLimit` at `90/3 = 30`)
Tested on EMR 5.21 with Google Maps Java SDK 0.2.6, 0.2.8 and 0.9.2.
