### ISSUE TITLE
Is GeoApiContext thread-safe?

### ISSUE THREAD

**Issue by marco-brandizi** [googlemaps/google-maps-services-java#207]
After having tested it, I realise GeoApiContext is not stateless, i.e., it's best to create one instance per api-key + settings set, because if you create an instance every time you need it, you will soon see a memory overflow (namely, a huge number of RateLimitExecutorDelayThread instances is generated). 

That said, is it thread-safe, or do I need to wrap it into ThreadSafe in a multi-thread application?

Would it be possible to document this in the code?

**Comment by domesticmouse** [comment]
The intent is to create one GeoApiContext per API Key, so that your API quota is respected. 

I'm not a hard core concurrency expert, so I'm not going to make hard guarantees about the thread safety of the code. If you want to review the code and suggest changes that make it thread-safe, I willingly accept PRs.

That said, it should be pretty easy to set up a producer/consumer thread safe queue in front of a GeoApiContext holding worker thread, given the API work is network bound, not CPU bound, so you'll not see any advantage of running GeoApiContext across multiple threads.
