### ISSUE TITLE
Unable to invoke no-args constructor for class com.google.maps.model.EncodedPolyline

### ISSUE THREAD

**Issue by aertsko** [googlemaps/google-maps-services-java#218]
I experience an exception when trying to use the Directions API on Google App Engine.`

`GeoApiContext context = new GeoApiContext(new GaeRequestHandler()).setApiKey("API_KEY");
DirectionsApiRequest request = DirectionsApi.getDirections(context, origin, destination);
DirectionsResult result = request.await();`

Resulting in 

`com.google.maps.errors.UnknownErrorException: Unable to invoke no-args constructor for class com.google.maps.model.EncodedPolyline. Register an InstanceCreator with Gson for this type may fix this problem.`

I can do successful requests to GeocodingAPI, but I always fail with the DirectionsAPI.

**Comment by BhalchandraSW** [comment]
#170

**Comment by nramanath** [comment]
I am facing this exact same issue. Is there any solution to this problem? 
Thanks.

**Comment by ArielY15** [comment]
I wrote my own Instance Creator for EcodedPolyline class and added it to the library. Then as suggested I registered it with Gson. It worked for me, is this a good solution?

[EncodedPolylineInstanceCreator.txt](https://github.com/googlemaps/google-maps-services-java/files/924253/EncodedPolylineInstanceCreator.txt)
[GaePendingResult.txt](https://github.com/googlemaps/google-maps-services-java/files/924254/GaePendingResult.txt)

**Comment by nramanath** [comment]
@ArielY15  - Thank you so much, it did really work. It's a good solution.

**Comment by domesticmouse** [comment]
@ArielY15 do you want to put those files into a PR?

**Comment by engeeaitch** [comment]
I've got exactly the same error as the OP.  Is there a workaround please?  @ArielY15 can you provide a bit more detail on what you did please?  Many thanks.

**Comment by ArielY15** [comment]
Gson requires a non arguments constructor for creating classes from Json files, but EncodedPolyline does not have one. 
So one solution might be adding a non argument constructor for the class, but since it is an immutable class the correct solution is to write an instance creator which is a Factory for building the class, and register Gson with it, so when Gson will try to create an instance of the class it will use the instance creator that has been registered instead of looking for non arguments constructor. 
What I've done is to write the instance creator for the EncodedPolyline and register Gson with it. 
The master branch is already updated with my code. 
Good luck!

**Comment by engeeaitch** [comment]
Great - many thanks - I've got it working now.

**Comment by domesticmouse** [comment]
I believe this issue was fixed by @Ariely15 with https://github.com/googlemaps/google-maps-services-java/pull/260
