### ISSUE TITLE
support Address Type "shopping_mall"

### ISSUE THREAD

**Issue by mmpower** [googlemaps/google-maps-services-java#226]
got warning:

`Feb 03, 2017 1:39:22 PM com.google.maps.internal.SafeEnumAdapter read
WARNING: Unknown type for enum com.google.maps.model.AddressType: 'shopping_mall'`

and got "UNKNOWN" as the result "type" value for sample code:
`GeocodingResult[] results = GeocodingApi.newRequest(context).address("ANSAR MALL      -152712, SHJ").await();`

Can "shopping_mall" be added to AddressType enum? or maybe better to make Address type a class instead of a enum so that it can support any new types in the future?

**Comment by domesticmouse** [comment]
I believe this was dealt with in https://github.com/googlemaps/google-maps-services-java/pull/275. Thanks!

**Comment by steveetl** [comment]
OK, I have a few more that should be added to AddressType:

bakery
pharmacy
supermarket
school
book_store
department_store
restaurant
real_estate_agency
bar
doctor
hospital
fire_station

Can these be generated from the database driving the input that google uses? 

Steve

**Comment by apjanke** [comment]
On Nov 13, 2017, I looked at https://developers.google.com/places/supported_types, which lists the address types currently supported by Google Maps API, and all the additional items listed by @steveetl appear, except for `supermarket`.

I'll add a PR to include these items. And +1 the idea of being able to generate these from Google's master list in some way. It'd be nice if the Google Maps API provided a way to enumerate the set of Address Types, so that we could generate the `AddressType` code from it. In the mean time, updating the list...

**Comment by apjanke** [comment]
PR added: #380. I included `supermarket` since you reported seeing it in the wild, even though it's not currently on Google's documentation page.
