### ISSUE TITLE
Retry for ZERO_RESULTS does not work

### ISSUE THREAD

**Issue by dimashi** [googlemaps/google-maps-services-java#280]
It looks like there is support in GeoApiContext for retrying in response is ZERO_RESULTS: toggleifExceptionIsAllowedToRetry(ZeroResultsException.class, true), but it does not work, because when 
{
  "results": [],
  "status": "ZERO_RESULTS"
}
is returned, no exception is thrown (I stepped through code in debugger). HTTP code is 200. Maybe there are cases when the same response comes back with not 200 but an error code, but not in my case. This happens on every ~5th request, i.e. not always but pretty often. If it helps address to geocode is "new york new york hotel casino 3790 las vegas boulevard south las vegas nv 89109 united states".

**Comment by domesticmouse** [comment]
I'm unsure what to do here. The issue is that the library cannot tell if the zero results is due to a failure in the backend, and should be retried, versus the situation where the query genuinely returns zero results, and continuously retrying would drain the user's QPD budget.

Thoughts?

**Comment by dimashi** [comment]
The library allows to do retry for any ApiException, but for most ApiExceptions retry does not make sense (IMO). Library declares ZeroResultsException, but does not throw it. And is ZERO_RESULTS really exceptional condition deserving overhead of throwing exception? So current design of the library also triggers some thoughts. I'd say if community considers design to be good, then we should follow it, and let user decide is it worth or not to retry when ZERO_RESULTS is returned. User should also specify maxRetryCount, library should never retry indefinitely.

**Comment by domesticmouse** [comment]
Actually, digging into the codebase, there is a max retry count. I'll look into this after the OkHttp3 conversion lands.

**Comment by shsachin** [comment]
User should be able to provide collection of exceptions that should be retried on.
Below looks hardcoded [here](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/GeoApiContext.java).

`this.exceptionsAllowedToRetry.add(OverQueryLimitException.class);`

**Comment by apjanke** [comment]
This almost sounds like a bug in the API, if it sometimes returns zero-results responses and you can't tell if that's an intermittent error or a legitimate "zero results found for this query" response.

FWIW, I am unable to reproduce a "zero results" response when repeatedly querying for various locations, including for "new york new york hotel casino 3790 las vegas boulevard south las vegas nv 89109 united states".

I do not think we should introduce a "retry on zero results" that retries on successful but empty-set responses unless we have good evidence that this is something the API does somewhat regularly. And if it does do that, I think that's a bug we should report up to the API maintainers.

**Comment by apjanke** [comment]
That makes sense; I understand there are system reasons why no results an be returned sometimes. But I'd expect the API to differentiate those, with maybe a flag to distinguish something like "I couldn't find any results within my best-effort usage-limit quota" from "I did a full search within my usage-limit quota and can positively say there are no results". Or do I not understand the system limitations, and that's just something that can't be distinguished?

**Comment by domesticmouse** [comment]
When you are operating in a distributed system consisting of 10,000 machines or more, the [split brain problem](https://en.wikipedia.org/wiki/Split-brain_(computing)) means that you cannot differentiate between the two cases you are thinking of. It turns out "I asked all of my back end services for results based on your query, and heard nothing back" means the same in both cases.

**Comment by apjanke** [comment]
Okay, gotcha.

In that case, maybe we _should_ supply a specific `retryOnZeroResults` option, next to the `exceptionsAllowedToRetry` option, that has the API retry on zero-results responses, in addition to exceptions. That would save the user the pain of having to write their own retry logic. And it doesn't seem like this should be handled by throwing an exception, because it's not necessarily an error.

**Comment by domesticmouse** [comment]
If we are going to retry on zero results, we need to do two things. Firstly, we need to delay by an appreciable amount of time to allow transient faults to rectify, and we need to retry a limited number of times to prevent infinite retries. I think we have logic in place in the retry code to handle the latter, but not the former case.

**Comment by apjanke** [comment]
> we need to delay by an appreciable amount of time to allow transient faults to rectify

Hmm. How about start with, say, 15 seconds, and do a binary exponential backoff?

**Comment by domesticmouse** [comment]
Sounds good to me. Thanks!

**Comment by shsachin** [comment]
User is already provided with retryOnZeroResults option. This can be done while creating context GeoApiContext.Builder().
`builder.setIfExceptionIsAllowedToRetry(ZeroResultsException.class, true);`

But this won't work as we are not throwing exception on ZERO_RESULTS. 

I think, we should let user/developer decide how to treat ZERO_RESULTS in their downstream application. I personally wanted to log it and mark status in my output object as ZERO_RESULTS. So that an appropriate message could be displayed to end-user.

May be we should modify successful() method implementation to consider this.

**Comment by domesticmouse** [comment]
More than happy to accept PRs that look at ways to fix this without breaking the API too much for existing users.

**Comment by domesticmouse** [comment]
For context, @micolous knows an awful lot more than I do about how the backends serving these queries are engineered. As such, I'm taking his advice on not re-trying on ZERO_RESULTS as final.
