### ISSUE TITLE
Version 0.1.21

### ISSUE THREAD

**Issue by IvanRF** [googlemaps/google-maps-services-java#285]
From 0.1.20 to 0.1.21 these libraries were added as dependencies:

- guava-22.0.jar	**2.45 MB**
- error_prone_annotations-2.0.18.jar	12 KB
- j2objc-annotations-1.1.jar	9 KB
- animal-sniffer-annotations-1.14.jar	4 KB

Is there really a need to depend on big library like `guava`? I use Maps services on a Java application and every new dependency makes my app installer bigger, that's why I ask this.

Also, when I change to 0.1.21 the eclipse IDE shows this error:

> The project was not built since its build path is incomplete. Cannot find the class file for `java.util.function.Predicate`. Fix the build path then try building this project

Is is possible that the minimum Java version needed to use the library has changed?

**Comment by domesticmouse** [comment]
My hand rolled rate limiter was leaking threads, which was really obvious when people used the library in a way I hadn't intended. Guava has a tidy rate limiter that doesn't leak. In theory we could cut'n'paste the rate limiter across to this project, but that has ongoing maintenance concerns.

And yes, that looks like we accidentally up'd the minimum Java version. I'm guessing Java 7 is required for your deployment situation?

As to size concerns, can you use something like proguard to do dead code elimination on the libraries?

**Comment by IvanRF** [comment]
> that looks like we accidentally up'd the minimum Java version. I'm guessing Java 7 is required for your deployment situation?

Yes, moving the `sourceCompatibility` to Java 7 removes that error. It was caused by a code change or by one of the new libraries?

> As to size concerns, can you use something like proguard to do dead code elimination on the libraries?

I didn't know proguard was able to do that, I will look into it. Thanks for the tip!

**Comment by apjanke** [comment]
Don't know if this is a concern here, but it looks like taking the Guava dependency [may be causing a build problem](https://github.com/googlemaps/google-maps-services-java/issues/286#issuecomment-318553235) with certain configurations in Android Studio, because Guava has a dependency on an old version of `com.google.code.findbugs:jsr305`. Might cause conflicts in other scenarios too.

**Comment by apjanke** [comment]
Maybe the Guava and other dependencies should be noted [in the README where the SLF4J dependency is noted](https://github.com/googlemaps/google-maps-services-java#installation)?

**Comment by apjanke** [comment]
Looks like this issue bit me, too. I'm using `google-maps-services-java` inside Matlab, which has an embedded JVM (Java 7) that ships with several bundled third party libraries, including Google Guava. Unfortunately, they ship an old Guava version 15.0, which doesn't seem to have a compatible version of the `RateLimiter`. So I can't upgrade past version 0.1.20 of `google-maps-services-java`, I think.

**Comment by domesticmouse** [comment]
I'm planning on rolling up a release once the current outstanding documentation PRs are merged in. The next release will include https://github.com/googlemaps/google-maps-services-java/pull/308 which hopefully will make this library happy on Java 7 again. Please feel free to make a PR for adding appropriate language about the dependency on Guava.

Thanks!

**Comment by apjanke** [comment]
No PR from me, sorry: I don't feel qualified to add language about the Guava dependency because I don't know enough about it's forward-compatibility behavior or google-maps-services-java's plans for how they're going to manage that dependency.

**Comment by domesticmouse** [comment]
@apjanke you are an active contributor to the project, I am more than open to hearing how you would like us to take this project forward. =)

**Comment by domesticmouse** [comment]
I believe the underlying issue in this bug report - Guava requiring Java8, will be fixed in v0.2.2

**Comment by apjanke** [comment]
Okay, a few things:

> I believe the underlying issue in this bug report - Guava requiring Java8, will be fixed in v0.2.2

I agree that v0.2.2 will fix the Java 8 dependency. Though it still has a new Guava dependency, which may still be a concern for some users, in the case where they have Guava dependencies through other means.

As far as adding README language about the Guava dependency: I dunno. Maybe it's worth listing the external Java library dependencies in the README after system requirements. But that info is also easily available in the gradle build files. I'd include it in the README if you want to make a commitment to limiting your dependencies to specific libraries & versions. Which maybe is a good idea.

My _personal_ preference would be for this library to not have a dependency on Guava at all. And that's because I'm using it inside Matlab, which has a dependency on an ancient version of Guava, and there's no chance of them upgrading any time soon. But I also recognize that Matlab users are probably a very small part of `google-maps-services-java`'s userbase (in fact, I wouldn't be surprised if I were the only one). I don't think it's unreasonable to take a dependency on Guava, and if you're going to do so, require a recent one; it's more my particular situation that's the oddity here.

One counterpoint: if you're freezing the Guava dependency at Guava v20 to get Java 7 support, you're basically giving up the maintenance gains of using an externally-maintained library, so it wouldn't be as much of a maintenance loss to just copy over their rate-limiter implementation into an internal package, since you won't be able to pick up future updates from them anyway.

Again, this is just my personal preference due to the platform I'm working in, and is probably not at all representative of your typical user. And the old version of this library is working just fine for me; I'm under no pressure to upgrade. Just a) anticipating the future when I may want to upgrade to a new version (e.g. if this lib adds stuff to facilitate caching), and b) I just like to use current, supported versions of third-party dependencies, especially if I can contribute back.

I really don't know how widespread usage of Guava or dependencies on particular versions of it are, so I don't know how much this would affect the rest of your user base. And that's really what should drive decisions here.

**Comment by domesticmouse** [comment]
If you want to have a go at pulling across the required classes for Guava's rate limiter I'll review and commit.

**Comment by apjanke** [comment]
Sweet! I'll take a swing at it tomorrow.

**Comment by apjanke** [comment]
Sorry for the slow response on this; Real Job interfered and took priority for a while.

This turned out to be feasible: doing a mechanical repackaging was ugly (187 classes in the transitive dependency tree!) but just hand-editing `RateLimiter` and `SmoothRateLimiter` and their immediate dependencies resulted in just a handful of classes to copy over.

I've put together a PR that pulls over the required classes and methods from Guava into a new `com.google.maps.internal.ratelimiter` package and eliminates the Guava dependency: https://github.com/googlemaps/google-maps-services-java/pull/351. Let me know what you think! It turned out to be not too much code copied over, so it might be a reasonable thing to do. (And it would be nice for me, because I'd get to use the current versions in my project!)

**Comment by domesticmouse** [comment]
Merged! I'll roll a release in the next week or so.
