### ISSUE TITLE
Support for region parameter in Text Search request on Places API

### ISSUE THREAD

**Issue by mdelmoral** [googlemaps/google-maps-services-java#534]
Reading the [documentation](https://developers.google.com/places/web-service/search#TextSearchRequests) there is an optional parameter `region` for the request 

`https://maps.googleapis.com/maps/api/place/textsearch/output?parameters`

and it is impossible to set this parameter using the Places API because is not supported.

**Comment by domesticmouse** [comment]
We gratefully accept Pull Requests =)

**Comment by apjanke** [comment]
I'll PR this.

There's also an optional `language` parameter we could add.

`region` takes a ccTLD domain code. `language` takes a language code, and there's a known (but "often" updated) [list of supported languages](https://developers.google.com/maps/faq#languagesupport). Should the `region` and `language` arguments be enums (or otherwise validated strings), or just leave them open to arbitrary string inputs?

**Comment by domesticmouse** [comment]
I think you will find that `language` parameter is handled in the base class. Pretty much all of the APIs take it as a parameter.

**Comment by apjanke** [comment]
Right you are. I see it now.

**Comment by apjanke** [comment]
Here's a PR: https://github.com/googlemaps/google-maps-services-java/pull/538

**Comment by domesticmouse** [comment]
Thank you Andrew =)

**Comment by apjanke** [comment]
Any time. 👍
