### ISSUE TITLE
Your project googlemaps/google-maps-services-java is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [googlemaps/google-maps-services-java#535]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  org.apache.httpcomponents httpclient (build.gradle)
  version: 4.5.6

  Jira issues:
  Support relatively new HTTP 308 redirect - RFC7538
  affectsVersions:3.1 (end of life),4.5.6
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1946?filter=allopenissues

  2  commons-lang commons-lang (build.gradle)
  version: 2.6

  Jira issues:
  Remove unnecessary synchronization from registry lookup in EqualsBuilder and HashCodeBuilder
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1230?filter=allopenissues
  LocaleUtils - DCL idiom is not thread-safe
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-803?filter=allopenissues
  Exception when combining custom and choice format in ExtendedMessageFormat
  affectsVersions:2.5;2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-917?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by apjanke** [comment]
@FDU-SE-LAB Would you mind providing contact info (i.e. an email and a website) on your GitHub profile?

I think you might be over-selling your results here. None of these bugs look "major" or "critical" to me. Still, probably worth upgrading to avoid them. Apache's internal labeling of these as "major" in their Jira might not correspond to their impact on client projects.

HttpClient is still at 4.5.6; the version with a fix for that bug is 5.0, which is still in beta. GMSJ probably won't want to upgrade to it until a non-beta release is out.

The commons-lang upgrade is probably pretty easily doable. I'm guessing GMSJ is currently on commons-lang 2.x because of a Java version dependency that's no longer applicable? (commons-lang 3.x requires Java 1.7+, and GMSJ now requires Java 1.8.)

**Comment by domesticmouse** [comment]
I'm curious which version this analysis was run against. Near as I can tell the current release, version 0.9.1, which has been in circulation for about a month, is already at the advised version of HTTP Client and Commons Lang.

See https://github.com/googlemaps/google-maps-services-java/blob/f8af5c7ece68ff7805630b67a8bd84d43eec63b7/build.gradle

**Comment by domesticmouse** [comment]
Oh wait, I misread your warning. I agree with @apjanke, I'm avoiding upgrading to beta versions.

**Comment by domesticmouse** [comment]
Closing this issue, as we will upgrade HTTP Client when 5.0 is released.
