### ISSUE TITLE
Direction Api Request call backs did not call 

### ISSUE THREAD

**Issue by Muhammadwahab** [googlemaps/google-maps-services-java#552]
Hi,I use Java Client library in android and found a unexpected issue in direction Api call backs,when user change device date and then call direction Api Neither onResult and onFailure call back function execute .I did not show any message to user and app stuck in map screen.When i kill application and open again direction Api working fine ?

**Comment by domesticmouse** [comment]
This library isn't designed for use in Android, per the README.

**Comment by acarlstein** [comment]
> 
> 
> This library isn't designed for use in Android, per the README.

By any chance, do you know what library is designed for use in Android then?

**Comment by domesticmouse** [comment]
I'd start with https://developers.google.com/maps/documentation/android-sdk/overview. I'm sure there are utility libraries that layer on top, but I don't know them off hand.

**Comment by arriolac** [comment]
Heya! Since version [0.19.0](https://github.com/googlemaps/google-maps-services-java/releases/tag/v0.19.0) of this library, we lifted the previous limitation since you now can apply API key restrictions while using this library on Android. If there are any Android-specific incompatibilities, please file an issue.
