### ISSUE TITLE
[publish.yml]: Deploy to maven central not working

### ISSUE THREAD

**Issue by rems** [googlemaps/google-maps-services-java#680]
Hi,

I was looking for release 0.12.0 in maven central, but it is not deployed.

I found the github action to deploy. It seems in error.

https://github.com/googlemaps/google-maps-services-java/runs/610585977?check_suite_focus=true

Thank you

**Comment by arriolac** [comment]
Thanks for reporting. I'm aware that the `publish.yml` workflow needs some work which is why I released a new artifact locally yesterday. However, it appears that it has not yet been synced with maven central yet which I'm working towards resolving. In the meantime, I've uploaded the `.jar` artifacts to the [0.13.0](https://github.com/googlemaps/google-maps-services-java/releases/tag/v0.13.0) release which you can download right now.

**Comment by arriolac** [comment]
I was able to resolve the maven issue, you should now be able to download the 0.13.0 version on maven central. I'll keep this issue open until the error on the github publish action is resolved.

**Comment by rems** [comment]
Thank you for uploading 0.13.0 :+1:
