### ISSUE TITLE
Allow for multiple types in PlaceAutocompleteRequest

### ISSUE THREAD

**Issue by kdoomsday** [googlemaps/google-maps-services-java#696]
PlaceAutocompleteRequest allows restricting via a call to types(PlaceAutocompleteType type). This, however, constrains you to a single value of the enum. The general API allows restricting to more than one type.

  I believe there should be a mechanism for passing more than one value to the types() method, or having multiple calls to types() accumulate the values, instead of replacing them.

**Comment by diicar** [comment]
in version 0.15.0, there is 2 methods but we cant pass a list of types, it would great addition because in my case, I'm only interested two types : ADDRESS or ESTABLISHMENT
`public PlaceAutocompleteRequest type(PlaceAutocompleteType type)`
And 
`public PlaceAutocompleteRequest types(PlaceAutocompleteType types)`

thanks
