### ISSUE TITLE
Display IP address used when RequestDeniedException

### ISSUE THREAD

**Issue by hth** [googlemaps/google-maps-services-java#76]
"This IP, site or mobile application is not authorized to use this API key" makes sense, but it would be nice to know which IP is being sent. 

Constructive error message would help educate user on steps to be taken for resolving this error.

**Comment by markmcd** [comment]
Great idea - the API itself doesn't return this at the moment, so it'll need to get added there first. Would you mind filling the feature request in the [Maps API issue tracker](https://code.google.com/p/gmaps-api-issues/issues/entry?labels=Type-Enhancement&status=New) first?

**Comment by hth** [comment]
Yes that would resolve the bigger issue, but 'google-maps-services-java' is making the same call to the API. At least 'google-maps-services-java' should be able to list the IP it has used to make this API call. Simply put, it does not matter what Maps API is returning, but what IP 'google-maps-services-java' service is calling from is the matter here.

I will still file a feature request with 'Maps API' but this issue can be independent of 'Maps API'.

**Comment by markmcd** [comment]
The only IP that the client library has access to is the IP on the interface making the outgoing request. The issue is that this is unlikely to be the same IP that is hitting the API (due to NAT). If we surface this IP in the error message, it implies that the user should add it to the console, which would (probably) not correct the error.

Generally speaking, I think it is better to show no information in favour of showing information that is possibly incorrect.

**Comment by hth** [comment]
I agree with you on that. 
On a side note: My network does not have a NAT.

The problem I have encountered while executing test below using API key is that it fails for me with un-authorized error message.
      
     # Run the tests
     $ API_KEY=AIza.... ./gradlew test

Allowed referers on Google Dev Consoles are listed below. 

     **hidden*.*example.com/*
     localhost

They seem to work when I directly hit the endpoint 'https://maps.googleapis.com/maps/api/geocode...'. But when using 'google-maps-services-java' I get un-authorized access error message. I do not have a clue what is being sent to Google Map API. Well I can use wireshark, but then I am getting into something which I do not want to. I expect it should pass consistently or fail consistently when I use the endpoint or 'google-maps-services-java'. 

If you can provide some insight then I do not mind doing diagnosis. If nothing else, then may be, by tomorrow night I will get wireshark fired up.

**Comment by markmcd** [comment]
You'll get a RequestDeniedException if the API is not enabled for that key (that's a separate step in the [console](https://console.developers.google.com/)).

Since you're talking about hostnames, it sounds like you might be setting up a browser key. To use this library you'll want to use a server key, as no referrer headers will be set in a server environment.

**Comment by hth** [comment]
Indeed you are right. I have been using browser key which starts with same 'AIza...'.  After setting up server key, there is a 15 minutes lag until it kicks in. After that everything worked really smooth. 

I had almost walked away. Really appreciate for pointing me in the right direction. 

Filed bug - https://code.google.com/p/gmaps-api-issues/issues/detail?id=7726

This issue can be considered as closed. Please open if there is anything else to be added.
